---
- name: Luminous-dental-ec2
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Luminous-dental-ec2
      ec2:
        key_name: dental-key
        instance_type: t2.nano
        image: ami-0c55b159cbfafe1f0  
        wait: yes
        region: us-west-2  
        group: your_security_group  
        count: 1
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"
